name: "Build firmware artifacts on push"
on: push


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install pyhon
        uses: actions/setup-python@v2

      - name: Install pio
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade platformio

      # Get the current date and time, in the timezone specified above, for use later.
      - name: Get current date and time
        id: date
        run: echo "::set-output name=date::$(TZ='${{ env.Timezone }}' date +'%Y-%m-%d %T')"

      # Get the current date
      - name: Get current date
        id: date_only
        run: echo "::set-output name=date_only::$(TZ='${{ env.Timezone }}' date +'%Y-%m-%d')"



      - name: Build t841 noserial
        run: pio run --project-dir ./Code --environment attiny841_noserial
      - name: Rename t841 noserial firmware
        run: |
          mv ./Code/.pio/build/attiny841_noserial/firmware.hex ./Code/.pio/build/attiny841_noserial/megadesk-$GITHUB_REF_NAME.hex
          FILENAME=./Code/.pio/build/attiny841_noserial/megadesk-$GITHUB_REF_NAME-t841-noserial.hex
          echo "FILENAME=$FILENAME" >> $GITHUB_ENV


      - name: Build t841 serial
        run: pio run --project-dir ./Code --environment attiny841_serial
      - name: Rename t841 serial firmware
        run: |
          mv ./Code/.pio/build/attiny841_serial/firmware.hex ./Code/.pio/build/attiny841_serial/megadesk-$GITHUB_REF_NAME-serial.hex
          SFILENAME=./Code/.pio/build/attiny841_serial/megadesk-$GITHUB_REF_NAME-t841-serial.hex
          echo "SFILENAME=$SFILENAME" >> $GITHUB_ENV

      - name: Build t1624 noserial
        run: pio run --project-dir ./Code --environment attiny1624_noserial
      - name: Rename t1624 noserial firmware
        run: |
          mv ./Code/.pio/build/attiny1624_noserial/firmware.hex ./Code/.pio/build/attiny1624_noserial/megadesk-$GITHUB_REF_NAME.hex
          FILENAME=./Code/.pio/build/attiny1624_noserial/megadesk-$GITHUB_REF_NAME-t1624-noserial.hex
          echo "FILENAME=$FILENAME" >> $GITHUB_ENV


      - name: Build t1624 serial
        run: pio run --project-dir ./Code --environment attiny1624_serial
      - name: Rename t1624 serial firmware
        run: |
          mv ./Code/.pio/build/attiny1624_serial/firmware.hex ./Code/.pio/build/attiny1624_serial/megadesk-$GITHUB_REF_NAME-serial.hex
          SFILENAME=./Code/.pio/build/attiny1624_serial/megadesk-$GITHUB_REF_NAME-t1624-serial.hex
          echo "SFILENAME=$SFILENAME" >> $GITHUB_ENV
        

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.BaseFileName }}-${{ steps.date_only.outputs.date_only }}
          path: ${{ env.OutputFolder }}/**
